### ISSUE TITLE
psbody cannot import 'plyutils'

### ISSUE THREAD

**Issue by quanzhou-li** [otaheri/GrabNet#10]
Hi, Thanks for your wonderful research work!

I am working on a research project and I'm highly interested in adapting your model into our work. I followed the steps of the installation instructions, but when I tried to run grab_new_objects.py to generate grasps for unseen objects, it constantly gave the error that 'plyutils' cannot be imported. I'm wondering if you can give a hand on how to fix this. Thanks very much!

![image](https://user-images.githubusercontent.com/33806420/133892269-20ae8b99-9037-49c4-aa4a-f27e05101fcf.png)

**Comment by otaheri** [comment]
@quanzhou-li Thank you for the interest in our work. I have checked the error, it seems that it comes from the psbody.mesh package and not from the GrabNet code. Have you tried installing the package from source as it is described in the [repo](https://github.com/MPI-IS/mesh)?

**Comment by quanzhou-li** [comment]
Hi Omid, thanks for your reply! I followed the psbody.mesh repo above to reinstall the package and the issue was resolved. It was previously because I didn't get the boost libraries installed properly. I am closing this issue :) 

Thanks again and have a nice day!
