### ISSUE TITLE
Permission Issue: Not able to access data in the Colab example

### ISSUE THREAD

**Issue by ltejedor** [otaheri/GrabNet#21]
Hello, using the Colab example from this project's README. 

On line:
`!source scripts/prepare_data.sh`
I get the error:
```
/usr/local/lib/python3.10/dist-packages/gdown/parse_url.py:44: UserWarning: You specified a Google Drive link that is not the correct link to download a file. You might want to try `--fuzzy` option or the following url: https://drive.google.com/uc?id=1L_We51j5FwIo5PeLvAK_9I3ZuFU_IWAq
  warnings.warn(
Downloading...
From: https://drive.google.com/file/d/1L_We51j5FwIo5PeLvAK_9I3ZuFU_IWAq/view?usp=sharing
To: /content/GrabNet/data/view?usp=sharing
84.4kB [00:00, 545MB/s]
unzip:  cannot find or open grabnet_data.zip, grabnet_data.zip.zip or grabnet_data.zip.ZIP.
rm: cannot remove 'grabnet_data.zip': No such file or directory
mv: cannot stat 'data/grabnet_data/refinenet.pt': No such file or directory
mv: cannot stat 'data/grabnet_data/coarsenet.pt': No such file or directory
```

When I go to the link directly, I'm able to see the files but not download them. Please help :)

**Comment by ltejedor** [comment]
I have access to the GrabNet data here - https://grab.is.tue.mpg.de/download.php - but there's a lot of it! I'm not sure which part corresponds to the Google Drive link referenced above.

**Comment by otaheri** [comment]
Hi @ltejedor,
Thanks for your interest in our work. I just checked Google Drive link for the files and it works fine on my end. Also, on our website, there are two download sections: 1. the GRAB dataset (you don't need this). 2. The GrabNet dataset (you should download this. Then please use the unzip code from our repo to extract the data. Please follow the instruction and it should work fine.
Please see the snapshot below for the data required to train GrabNet.

![image](https://github.com/otaheri/GrabNet/assets/19238978/4e841ca0-e3e7-4350-b068-93f9b52358a8)

**Comment by ltejedor** [comment]
Thank you for the reply. Did you try to use the Colab? While the Drive link loads, I'm not able to download or actually access any of the files, which I believe is leading to the Permissions issue referenced above.

<img width="929" alt="Screenshot 2024-03-08 at 10 09 11 AM" src="https://github.com/otaheri/GrabNet/assets/4766096/0ee40857-d0b3-41f1-875c-c89b6c6bfefa">

**Comment by otaheri** [comment]
I updated the colab notebook, now you should be able to manually download the file and put it in the right folder to continue.
