### ISSUE TITLE
Dataset Question: Where in the data is "tools -> object_meshes"?

### ISSUE THREAD

**Issue by ltejedor** [otaheri/GrabNet#22]
Hello! I'm trying to download the GrabNet dataset to attempt to re-train the model. 

I downloaded and unzipped the data, but don't see the object_meshes folder under tools. Subject_meshes are available in the image below. Should I use the object meshes under the GRAB dataset?

Thank you!

<img width="611" alt="Screenshot 2024-04-03 at 11 20 51 PM" src="https://github.com/otaheri/GrabNet/assets/4766096/64e4feea-4e08-4d68-a824-1a9da98c3c3e">

<img width="1127" alt="Screenshot 2024-04-03 at 11 23 07 PM" src="https://github.com/otaheri/GrabNet/assets/4766096/598fbce8-35c1-4b7f-b9b0-50fc7bc3a40f">

**Comment by ghost** [comment]
hi how you fix this? thanks!
